### PR TITLE
On a pinned track resize, the mouse and the border being moved are dislocated

### PR DESCRIPTION
**Pull request by ALevansSamsung**
#### What it does

Addresses this [Sokatoa Issue](https://github.com/android-graphics/sokatoa/issues/1285)

#### How to test

Pin a track.
Resize the track using the bottom border.
It shouldn't become very dislocated
Resize the track in the pinned group as it should have the same effect

### CODE REVIEW

**Comment by jcortell68** [comment]
What does the new `pinnedGroup` property represent? Groups can't be pinned, so the name is a bit surprising to me.

**Comment by ALevansSamsung** [comment]
Its meant to differentiate between a Track Group created for the Pinned set at the top of the timeline vs the track in the main scrollable set of the timeline.  When a track is pinned there are then two copies of it, one in the pinned section, and one in the main view.  Before this PR, if you resized the track in the main view the mouse would be severely dislocated, because both copies of the track were being changed which would cause the main view track's bottom border to be 2x as far as expected based on the mouse's movement.  When the user is resizing the track in the pinned area we don't need to compensate for the double movement, therefore I needed to be able to differentiate between the track in the main view vs the pinned area.  I'm more than willing to change the name of the property.

**Comment by jcortell68** [comment]
> Its meant to differentiate between ...

Ah...I had no idea that resizing a track resized both the pinned and normal track! Now the change makes a lot more sense :-) I think some comments in the code sharing this insight would be very helpful. The divide by two just doesn't make much sense otherwise.

Also didn't realize pinned tracks are in a Track Group, since unlike a normal track group, there is no expansion/title track for the group. Maybe `pinnedVersion` or `pinnedCopy` or just `pinned`. Any of those would be clearer, to me anyway

**Comment by ALevansSamsung** [comment]
I miss-typed.  `differentiate between a Track Group created` was meant to be `differentiate between a Track created`.  Regardless when we implement pinning for track groups this same solution will be needed.

**Review by jcortell68 — APPROVED** [review]

**Pull request merged**
