### PR TITLE
SQL Theming

### PR DESCRIPTION
**Pull request by ALevansSamsung**
Before:
image
After:
SQL_new

### CODE REVIEW

**Comment by jcortell68** [comment]
Can we get a little darker shading on the alternate rows? Maybe throwing in a tiny bit of blue (or green)? Just something to make the alternate rows stand out a bit more.

**Comment by ALevansSamsung** [comment]
Not really, the colors I'm using to theme Perfetto aren't defined by me.  They are Theia's themed and defined colors.  In high contrast the alternate rows actually do show up a bit more blue.  We could also at some point add in our own Theia theme at some point as well.
SQL_High_Contrast

**Comment by jcortell68** [comment]
OK. Not a big deal.

**Review by jcortell68 — APPROVED** [review]

**Comment by ALevansSamsung** [comment]
The "Show debug track" button seems to open a "pop-up" which is controlled by SCSS files that don't seem to be showing up in the final CSS causing the pop-up to look bad. @martin-fleck-at do you know why this file isn't being added?  Also using the "popup" that appears also seems to cause an error to be thrown (at least it did for me), so I'm wondering what value it adds.

**Comment by ALevansSamsung** [comment]
> The "Show debug track" button seems to open a "pop-up" which is controlled by SCSS files that don't seem to be showing up in the final CSS causing the pop-up to look bad. @martin-fleck-at do you know why this file isn't being added? Also using the "popup" that appears also seems to cause an error to be thrown (at least it did for me), so I'm wondering what value it adds.

https://github.com/android-graphics/sokatoa/issues/709

**Comment by cdamus** [comment]
Query results look great in light mode, including the alternate-row shading. So that's great!

CleanShot 2023-11-16 at 16 42 36

However, the query input field, itself, looks like it's stuck in dark mode:

CleanShot 2023-11-16 at 16 42 13

Is that something we should address?

**Comment by ALevansSamsung** [comment]
> However, the query input field, itself, looks like it's stuck in dark mode:
> 
> CleanShot 2023-11-16 at 16 42 13
> 
> Is that something we should address?

I think the intention by the Perfetto team was to make that section look like a terminal window.

**Comment by cdamus** [comment]
> I think the intention by the Perfetto team was to make that section look like a terminal window. For instance if you type in it your text will be green

Thanks, @ALevansSamsung , I think you must be correct. It's so incongruous in the UI, to me a baffling design decision. Let's park it with the black group headers.

**Review by cdamus — APPROVED** [review]

**Pull request merged**
